### ISSUE TITLE
Deployments class in a separate project

### ISSUE THREAD

**Issue by smiderle** [ingwarsw/arquillian-suite-extension#18]
Is it possible to implement the deployments class (@ArquillianSuiteDeployment) in a project separate, with all settings deploy and pom.xml, and be reused by other projects, that will implement only tests (@Test), using the deploy done by the first project

**Comment by rumil** [comment]
From my experience it is not working like that by default. The issue I found is the way Reflections scans for classes annotated with ArquillianSuiteDeployment - it scans only target/classes and target/test-classes but my suite deployment class is inside test jar dependency,thus not being found

**Comment by ingwarsw** [comment]
Sorry I didnt have tome to look at it..

If you really need It will be probably not so difficult to add that option.

**Comment by rumil** [comment]
For now I've managed to work around it in a hackish way (I basically have my own ArquillianSuiteExtension which calls Reflections differently).
But long term upstream solution (some configuration option) would be great.
