### ISSUE TITLE
NPE when using java 8

### ISSUE THREAD

**Issue by Panchitoboy** [ingwarsw/arquillian-suite-extension#22]
Sorry for my bad english:

        <dependency>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
            <version>0.9.8</version>
        </dependency>

This dependency has a problem with Java 8, It gives NPE when you do this:

		private static Class<?> getDeploymentClass() {
				Reflections reflections = new Reflections("");
				Set<Class<?>> results = reflections.getTypesAnnotatedWith(ArquillianSuiteDeployment.class, true);
				if (results.isEmpty()) {
					results = reflections.getTypesAnnotatedWith(ArquilianSuiteDeployment.class, true);
					if (results.isEmpty()) {
						return null;
					}
				}
				if (results.size() > 1) {
					for (Class<?> type : results) {
						log.log(Level.SEVERE, "arquillian-suite-deployment: Duplicated class annotated with @ArquillianSuiteDeployment: {0}", type.getName());
					}
					throw new IllegalStateException("Duplicated classess annotated with @ArquillianSuiteDeployment");
				}
				return results.iterator().next();
			}

Can you update the project to the last one? (0.9.9) That fix the problem

**Comment by ingwarsw** [comment]
I dont remember why but i reverted to 0.9.8..

I will look at it..

**Comment by johnament** [comment]
My guys just ran into this too.  Turns out, if you just update your project (consumer of arquillian suite) to use reflections 0.9.9 it's all good.

**Comment by ingwarsw** [comment]
Could you check if now master branch will work for you?

If yes I will release it.
