### ISSUE TITLE
Multiple Isolated Suites

### ISSUE THREAD

**Issue by rnc** [ingwarsw/arquillian-suite-extension#23]
Is it possible to have multiple isolated suites? e.g. run one set of tests together and another set together? 

Is it possible to run some tests together and the rest in individual deployments?

**Comment by ingwarsw** [comment]
Regarding first question.
Its possible to have different deployments and run different tests on different deployments.
You just need to name deployments and then use @OperateOnDeployment annotation on test or test class to run it on that deployment.
You can look at my tests.. im using multiple deployments there..

And second one..
I was thinking about that but its quite complicated.
For now you can use solution provided at question one.
Create small deployments for tests that you need.
But there is one issue with that approach... all deployments needs to be in one class.. and it can grow really fast..
