### ISSUE TITLE
Doesn't work for managed Wildfly container (?)

### ISSUE THREAD

**Issue by johnedo1234** [ingwarsw/arquillian-suite-extension#28]
I'm having trouble getting the suite extension working with a managed Wildfly container. The first test class in the suite executes properly, but all subsequent test classes fail.

Here's what seems to be going on:
1. Start container
2. Deploy test.war (in memory only; not found in standalone/deployments)
3. Run test class 1
4. Stop container (test.war disappears from memory)
5. Start container
6. Run test class 2 (oops, there's no test.war anymore)

Are managed containers simply not supported by the suite extension, or is it a problem with the particular container adaptor?

It seems that either the deployment needs to be written to disk, or the container shouldn't be restarted.

Versions:
- Arquillian Version 1.1.5.Final
- Arquillian Suite Extension Version 1.1.2
- Arquillian Persistence Extension Version 1.0.0.Alpha7
- Arquillian Wildfly Container Managed Version 8.1.0.Final
- Wildfly Version 8.1.0.Final

Any help would be appreciated!

**Comment by ingwarsw** [comment]
Check with wildfly 10 if possible..
Should work..
