### ISSUE TITLE
Deployments are created even if not used

### ISSUE THREAD

**Issue by pesche666** [ingwarsw/arquillian-suite-extension#36]
Hi 

I am just working on a  small test project with suite-extension. I have a Suite class with three @Deployment methods defined.

If running a single @Test method (or class) from the IDE I noticed that arquillian is really only running that single test but three archives are created nonetheless. If you have several deployments that are large this could be a huge loss of time during daily development.  

Is there a way to streamline this?
Thanks!

**Comment by ingwarsw** [comment]
As far as I remember there is no easy way of doing that..

You could try disabling some deployments in runtime..
Mayby that would help..
