### ISSUE TITLE
not working on wildfly 10

### ISSUE THREAD

**Issue by artorius82** [ingwarsw/arquillian-suite-extension#39]
Because of dom4j dependency in compile scope.
The reflections jar brings dom4j as  a transitiv dependency into the project. 
Please change the scope of dom4j to test/provided or just make it an optional dependency.

**Comment by ingwarsw** [comment]
Could you check if branch feature/new_arquillian is working for you?

**Comment by ingwarsw** [comment]
Released as v1.1.4.. Check if will work for you..
