### ISSUE TITLE
Not working with arquillian-core 1.1.13.Final

### ISSUE THREAD

**Issue by reitzmichnicht** [ingwarsw/arquillian-suite-extension#40]
Suite Extension tries to access ManagerImpl.DEBUG which seems to be removed in the new core version.
Would be great to have an update for this great extension to be able to use the new Arquillian Universe dependencies.

**Comment by ingwarsw** [comment]
Could you check if branch feature/new_arquillian is working for you?
If yes I will release it..

**Comment by charleech** [comment]
I've tested against the `feature/new_arquillian`, it works properly.

**Comment by reitzmichnicht** [comment]
Thank you very much for the fast fix. Is a release of this branch planned in the near future?

**Comment by ingwarsw** [comment]
Working on it right now..

**Comment by ingwarsw** [comment]
Could you try version 1.1.4?

**Comment by reitzmichnicht** [comment]
Yes works great again. Thank you very much.
Any chance to get this extension into the arquillian universe bom?

**Comment by ingwarsw** [comment]
Your welcome :)

Dont think so...
Arquillian guys are working hard to make suites in arquillian itself..
AFAIK version 2.0 should have them..
