### ISSUE TITLE
Arquillian universe 1.2 compatibility

### ISSUE THREAD

**Issue by reitzmichnicht** [ingwarsw/arquillian-suite-extension#46]
Arquillian-suite-extension has now some upper bounds problems with the actual shrinkwrap version 3.1.3
I had to add the following two overrides:
  ```
    <dependency>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-utils</artifactId>
        <version>3.0.24</version><!-- arquillian-suite-extension vs shrinkwrap -->
      </dependency>
      <dependency>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-component-annotations</artifactId>
        <version>1.7</version><!-- arquillian-suite-extension vs shrinkwrap -->
      </dependency>
```

Would be cool to have a new version with updated dependencies.

**Comment by ingwarsw** [comment]
Hello..
Just updated arquillian bom to new one and it still have older version than needed by you.
I dont want to force new version at plugin level (I want to keep compatibility with arquillian version Im using).
