### ISSUE TITLE
Ability to disable extension?

### ISSUE THREAD

**Issue by commodis** [ingwarsw/arquillian-suite-extension#56]
While the extension is useful to run all tests in batch,
sometimes it is smart to only run a single test for example in development.

Is there some option to disable the extension?

Currently we are commenting out the `@ArquillianSuiteDeployment` annotation which is very error prone.

**Comment by ingwarsw** [comment]
Hello @commodis.

But if you want to run 1 test it should not be a problem to run just it..
You will have to deploy your "deployment" either for 1 test or for batch.. (and it should be same deployment)

If for whatever reason its not the case you can try using setting suite via arquilian.xml file and somehow generate it dynamically based on properties/params.

See documentation here..
https://github.com/ingwarsw/arquillian-suite-extension/blob/93c9e542ead1d52f45e87b0632bb02ac11f693c8/README.md#configuring-deployment-suite-class-by-in-arquillianxml

**Comment by commodis** [comment]
Thanks!

with a clean setup I could run a single tests without a problem.
I think the behavior change somewhere along.

Closing this issue and sorry for the inconvenience
