### ISSUE TITLE
Doesn't work with arquillian-jacoco

### ISSUE THREAD

**Issue by kraanerk** [ingwarsw/arquillian-suite-extension#6]
If one wants to gather test code coverage with arquillian-jacoco then arquillian-suite-extension can't be used. Their co-existence results in a StackOverflowError.

**Comment by leccyril** [comment]
i have same problem with new jacoco version full pom.xml:
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.real</groupId>
	<artifactId>RflowHR</artifactId>
	<version>0.1-SNAPSHOT</version>

	<properties>
	 	<argLine>-Xmx2048m</argLine>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
		<failOnMissingWebXml>false</failOnMissingWebXml>
		<version.jboss.spec.javaee.7.0>1.0.3.Final</version.jboss.spec.javaee.7.0>
		<default.scope>provided</default.scope>
		<test.scope>test</test.scope>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<repositories>
		<repository>
			<id>jcenter</id>
			<name>bintray</name>
			<url>http://jcenter.bintray.com</url>
		</repository>
	</repositories>


	<dependencyManagement>
		<dependencies>
			
			
			<dependency>
				<groupId>org.jboss.spec</groupId>
				<artifactId>jboss-javaee-7.0</artifactId>
				<version>${version.jboss.spec.javaee.7.0}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.jboss.arquillian</groupId>
				<artifactId>arquillian-bom</artifactId>
				<version>1.1.12.Final</version>
				<scope>import</scope>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			
			
		</plugins>
	</build>
	<packaging>war</packaging>
	<dependencies>
		<dependency>
			<groupId>com.real</groupId>
			<artifactId>AofCommon</artifactId>
			<version>1.7.7</version>
		</dependency>
		
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator-annotation-processor</artifactId>
			<version>5.3.4.Final</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>3.8</version>
		</dependency>
		<dependency>
			<groupId>org.easytesting</groupId>
			<artifactId>fest-assert</artifactId>
			<version>1.4</version>
		</dependency>
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
		</dependency>
		
		<dependency>
			<groupId>org.mock-server</groupId>
			<artifactId>mockserver-netty</artifactId>
			<version>3.10.4</version>
			<exclusions>
				<exclusion>
					<groupId>xerces</groupId>
					<artifactId>xercesImpl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>com.hierynomus</groupId>
			<artifactId>sshj</artifactId>
			<version>0.19.0</version>
		</dependency>
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.4</version>
		</dependency>
		<dependency>
			<groupId>commons-codec</groupId>
			<artifactId>commons-codec</artifactId>
			<version>1.10</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.spec</groupId>
			<artifactId>jboss-javaee-7.0</artifactId>
			<type>pom</type>
			<version>1.0.3.Final</version>
			<scope>${default.scope}</scope>
		</dependency>
		<dependency>
			<groupId>com.thoughtworks.xstream</groupId>
			<artifactId>xstream</artifactId>
			<version>1.4.9</version>
		</dependency>
		<dependency>
			<groupId>org.jboss.resteasy</groupId>
			<artifactId>resteasy-client</artifactId>
			<version>3.0.11.Final</version>
			<scope>${default.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-core</artifactId>
			<version>4.3.10.Final</version>
			<scope>${default.scope}</scope>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
			<version>2.8.5</version>
			<scope>${default.scope}</scope>
		</dependency>

		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.21</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.21</version>
		</dependency>

		
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.json</artifactId>
			<version>1.0.4</version>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-all</artifactId>
			<version>1.10.19</version>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>6.10</version>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.testng</groupId>
			<artifactId>arquillian-testng-container</artifactId>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.arquillian.protocol</groupId>
			<artifactId>arquillian-protocol-servlet</artifactId>
			<scope>${test.scope}</scope>
		</dependency>
		<dependency>
			<groupId>org.jboss.shrinkwrap.resolver</groupId>
			<artifactId>shrinkwrap-resolver-depchain</artifactId>
			<scope>${test.scope}</scope>
			<type>pom</type>
			<exclusions>
				
				<exclusion>
					<groupId>org.eclipse.sisu</groupId>
					<artifactId>org.eclipse.sisu.inject</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.sisu</groupId>
					<artifactId>org.eclipse.sisu.plexus</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.eu.ingwar.tools</groupId>
			<artifactId>arquillian-suite-extension</artifactId>
			<version>1.1.2</version>
			<scope>${test.scope}</scope>
		</dependency>
<dependency>
					<groupId>org.wildfly.arquillian</groupId>
					<artifactId>wildfly-arquillian-container-managed</artifactId>
					<version>2.0.2.Final</version>
					<scope>test</scope>
				</dependency>
	
	<dependency>
		<groupId>org.jboss.arquillian.extension</groupId>
		<artifactId>arquillian-jacoco</artifactId>
		<version>1.0.0.Alpha9</version>
		<scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.jacoco</groupId>
		<artifactId>org.jacoco.core</artifactId>
		<version>0.7.8</version>
		<scope>test</scope>
	</dependency>
	</dependencies>
	<profiles>
	<profile>
		<id>test-coverage</id>
		<build>
			<plugins>
				 <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.7.8</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-prepare-agent-integration</id>
                        <goals>
                            <goal>prepare-agent-integration</goal>
                        </goals>
                        <configuration>
                            <destFile>${project.build.directory}/jacoco-it.exec</destFile>
                        </configuration>
                    </execution>
                    <execution>
    					<id>jacoco-site</id>
    					<phase>verify</phase>
    					<goals>
       						 <goal>report</goal>
        					<goal>report-integration</goal>
   						 </goals>
					</execution>
                </executions>
            </plugin>

			</plugins>
		</build>
	</profile>
		<profile>
			<id>integration-tests-wildfly</id>
			<build>
				<plugins>
				 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                    <version>2.19.1</version>
                            <configuration>
                    <failIfNoTests>false</failIfNoTests>
                    <excludedGroups>org.jboss.arquillian.testng.Arquillian</excludedGroups>
                </configuration>
            	</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>2.19.1</version>
						
						<configuration>
							<systemPropertyVariables>
								<jboss.server.log.dir>${jboss.home.dir}/standalone/log</jboss.server.log.dir>
								<arquillian.launch>jbossas-managed</arquillian.launch>
								<jbossas.startup.timeout>240</jbossas.startup.timeout>
							
							</systemPropertyVariables>
							<includes>
								<include>**/*IT.java</include>
							</includes>

						</configuration>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>deploy-real</id>
			<distributionManagement>
				<repository>
					<id>releases</id>
					<name>Internal Releases</name>
					<url>http://rs-dev-01.real.net:8180/nexus/content/repositories/releases/</url>
				</repository>
				<snapshotRepository>
					<id>snapshots</id>
					<name>Internal Snapshots</name>
					<url>http://rs-dev-01.real.net:8180/nexus/content/repositories/snapshots/</url>
				</snapshotRepository>
			</distributionManagement>
		</profile>
		
	</profiles>
</project>
`

arquillian.xml:

`<?xml version="1.0" encoding="UTF-8"?>
<arquillian xmlns="http://jboss.org/schema/arquillian"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jboss.org/schema/arquillian http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

	
	<defaultProtocol type="Servlet 3.0" />
        
    
	<engine>
	       <property name="deploymentExportPath">target/</property>
	</engine>
    <extension qualifier="jacoco">
    <property name="excludes">*</property>
</extension>
    
    <container qualifier="jbossas-managed" default="true">
    
        <configuration>
            <property name="jbossHome">${env.JBOSS_HOME}</property>
            <property name="serverConfig">standalone-real-continuous-integration.xml</property>
             <property name="deploymentExportPath">target/arquillian</property>
             <property name="javaVmArguments">${argLine},jmx=true,includes=com.real.*</property>
             
            <property name="allowConnectingToRunningServer">true</property>
            <property name="startupTimeoutInSeconds">${startup.timeout:360}</property>


        </configuration>
    </container>`
