### ISSUE TITLE
Version 1.2.2 not avaiable in github releases but found on mvnrepository.com

### ISSUE THREAD

**Issue by omasseau** [ingwarsw/arquillian-suite-extension#73]
Hello,

I'm confused as there is no 1.2.2 release here : https://github.com/ingwarsw/arquillian-suite-extension/releases

But I see that the latest version on https://mvnrepository.com/artifact/org.eu.ingwar.tools/arquillian-suite-extension is 1.2.2.
Can this version be used or should I use 1.2.1 ?

**Comment by ingwarsw** [comment]
For whatever reason there was no release just tag with that version.
I just created release also.

Version 1.2.2 is latest one and proper one for use.
